name: crucible-ci

on:
  # run on push or pull request events for the master branch only
  pull_request:
    branches: [ master ]

  # allow for manual invocation from the actions tab
  workflow_dispatch:

jobs:
  crucible-ci-samples-fio-remotehost:
    name: crucible-ci-samples-fio-remotehost
    runs-on: ubuntu-latest

    steps:
    - name: Checkout rickshaw
      uses: actions/checkout@v2
      with:
        path: rickshaw

    - name: Checkout crucible-ci
      uses: actions/checkout@v2
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci

    - name: Run crucible-ci->integration-tests
      uses: ./crucible-ci/.github/actions/integration-tests
      with:
        artifact_tag: "samples-remotehost"
        ci_target: "engine"
        ci_target_dir: ${{ github.workspace }}/engine
        scenarios: "fio"
        run_samples: "3"
        ci_endpoint: "remotehost"

  crucible-ci-samples-fio-k8s:
    name: crucible-ci-samples-fio-k8s
    runs-on: ubuntu-latest

    steps:
    - name: Checkout rickshaw
      uses: actions/checkout@v2
      with:
        path: rickshaw

    - name: Checkout crucible-ci
      uses: actions/checkout@v2
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci

    - name: Run crucible-ci->integration-tests
      uses: ./crucible-ci/.github/actions/integration-tests
      with:
        artifact_tag: "samples-k8s"
        ci_target: "engine"
        ci_target_dir: ${{ github.workspace }}/engine
        scenarios: "fio"
        run_samples: "3"
        ci_endpoint: "k8s"
